docker/base/scripts/docker-entrypoint.sh
docker/conda/scripts/docker-entrypoint.sh

Make the default UID be 1001, rather than 9001.
In containers using Conda, create a new group with the specified GID,
if it does not alreqdy exist.

Change to UID and GID handling in containers

---

docker/conda/scripts/install_conda.sh

Update conda-build to 3.18.11
Don't explicitly install Python because this can install a version
incompatible with conda-build (unless we start pinning the Python
version).

Update conda-build to 3.18.11

---

docker/conda/scripts/docker-entrypoint.sh
docker/conda/ubuntu/12.04/Dockerfile

This fix uses groupmod to ensure that the conda GID is set to the
desired value in the entrypoint script.

Bugfix: setting the conda group GID

---

README.md
docker/Makefile
docker/base/ubuntu/18.04/Dockerfile
docker/base/ubuntu/18.04/README.md
docker/irods/ubuntu/18.04/Dockerfile
docker/irods/ubuntu/18.04/README.md

Add Ubuntu 18.04 base gosu image build
Add iRODS 4.2.8 Ubuntu 18.04 image build
Rename iRODS 4.2.7 image from 4.2 to 4.2.7 because even the minor
version is significant; the iRODS API has deprecations between the
minor versions, see https://github.com/wtsi-npg/baton/pull/224

Add iRODS 4.2.8 Ubuntu 18.04 image

---

README.md
singularity/Makefile
singularity/baton/baton-2.1.0.def
singularity/baton/baton-2.1.0.env
singularity/scripts/add_irods_apt_repository.sh
singularity/scripts/install_apt_tools.sh
singularity/scripts/install_build_tools.sh
singularity/scripts/uninstall_apt_tools.sh

Builds `baton` in a Singularity container. We are likely to need this given the difficulty of packaging iRODS clients with Conda.

Add baton 2.1.0 Singularity image built for iRODS 4.2.7

---

docker/conda/scripts/install_conda.sh

avoids certificate problems if base OS certs are not upgraded
by using certs from Conda by using Conda installed tools

install git and curl using Conda

---

README.md
docker/Makefile
docker/irods/scripts/configure_irods.sh

One minor tweak was required to the iRODS configuration script (iRODS 4.2.9 doesn't automatically get started during the build process).

Add an iRODS 4.2.9 server Docker container build to the Makefile

---

docker/irods/scripts/configure_irods.sh

Patch core.re to set the default resource to `testResc` because sometimes iRODS ignores the default resource set in either client or server config. The bug is still open after the release of iRODS 4.2.9, see: https://github.com/irods/irods/issues/4692
This bug affects:
4.2.7 (confirmed)
4.2.8 (not observed, fixed by accident?)
4.2.9 ?

Patch core.re to set the default resource

---

README.md
docker/Makefile
docker/irods/ubuntu/18.04/Dockerfile
docker/irods/ubuntu/18.04/README.md

Add iRODS 4.2.10
Make 4.2.10 the default if no version is specified. This is because
it's the 4.2.x release with the fewest known bugs.

Add iRODS 4.2.10

---

.github/workflows/pushing_container_image.yml

Allows containers to be pushed to GitHub Packages on release.

amend GHA for ubuntu to centos conda image change

---

docker/conda/scripts/install_conda_build.sh

Prevent Conda from being updated in an uncontrolled manner to a newer
version, when conda-build is installed. Without this change, we do not
know which version of Conda gets installed when images are built.

Prevent Conda from being updated when conda-build is installed

---

.github/workflows/push_container_image.yml

The GITHUB_ACTIONS argument was not passed to the Makefile during
building.
The GITHUB_ACTIONS argument was set incorrectly to the value of
github.action (although this makes no matyerial difference; the
variable must simply be set, its value is unimportant.

Fix Github Actions build Makefile arguments

---

docker/Makefile
docker/conda/minideb/bullseye/Dockerfile
docker/irods/ubuntu/16.04/Dockerfile
docker/irods/ubuntu/18.04/Dockerfile
docker/irods_clients/minideb/bullseye/Dockerfile
docker/irods_clients/scripts/start_client_container.sh
docker/irods_clients/ubuntu/Dockerfile
docker/irods_clients/ubuntu/README.md
docker/irods_clients_dev/ubuntu/Dockerfile

Add a Dockerfile supporting at least Ubuntu 18.04 and 20.04.
Update the client container startup script to use the new image by
default.
Update the Makefile to build iRODS 4.2.11 clients on Ubuntu 18.04.
Built on #44 which should be merged first

Add Ubuntu-hosted iRODS clients without using Conda

---

docker/irods_clients/ubuntu/Dockerfile
singularity/scripts/singularity-exec-docker
singularity/scripts/singularity-service-docker
singularity/scripts/singularity-wrapper

Allow the user to choose at install time whether the wrappers generated use singularity run, exec or exec in a service instance.
Add logging to syslog for service instance wrappers.

Add choice of run or exec wrapper behaviours

---

docker/Makefile
docker/base/ubuntu/22.04/Dockerfile
docker/base/ubuntu/22.04/README.md
docker/irods/scripts/configure_irods.sh
docker/irods/ubuntu/22.04/Dockerfile
docker/irods/ubuntu/22.04/README.md

Adds a server container using iRODS Debian packages build nightly from 4-3-stable.
~~Currently a draft because the packages URL in the Dockerfile is pointing to @kjsanger 's fork of the package-building repo, at the moment.~~

Add iRODS 4-3-stable server nightly build

---

docker/Makefile
docker/irods_clients/ubuntu/16.04/Dockerfile
docker/irods_clients_dev/README.md
docker/irods_clients_dev/ubuntu/16.04/Dockerfile
docker/irods_clients_dev/ubuntu/16.04/README.md
singularity/scripts/singularity-wrapper

This change is stacked on #67 and #65 so please review those first.

Feature/irods 4.2.7 client images

---

docker/Makefile
docker/irods_clients/ubuntu/16.04/Dockerfile
docker/irods_clients/ubuntu/22.04/Dockerfile
docker/irods_clients/ubuntu/Dockerfile

Update to baton 4.2.0, which builds on iRODS 4.2.7 through to 4.3-nightly (except 4.3.0).
Remove some unnecessary tools from the Docker builds.

Update to baton 4.2.0

---

.github/workflows/create-release.yml
.github/workflows/nightly-build.yml
docker/irods_clients/ubuntu/16.04/Dockerfile
docker/irods_clients/ubuntu/22.04/Dockerfile
docker/irods_clients/ubuntu/Dockerfile
docker/irods_clients_dev/ubuntu/16.04/Dockerfile
docker/irods_clients_dev/ubuntu/Dockerfile

This is to work around the issue that docker buildx cannot build ona base image that it has just built. See https://github.com/docker/buildx/issues/1453

Force docker buildx to use the default builder

---

.github/workflows/create-release.yml

GitHub requires the full SHA, not a shortened version.

Use the full SHA when declaring an Action version

---

docker/Makefile

Adding --pull to all builds breaks local builds because Docker expects the pulled image to be in a registry.
This change is a compromise which uses --pull only for third party images which are always obtained from a registry and avoids it for images built locally by the Makefile.

Fix local builds broken by adding --pull globally

---

docker/irods/ubuntu/22.04/Dockerfile
docker/irods_clients/ubuntu/22.04/Dockerfile
docker/irods_clients_dev/ubuntu/22.04/Dockerfile

The 4-3-stable branch has been tagged upstream as 4.3.1, which changes the name of the packages created.

Update nightly package names for 4.3.1 tag

---

README.md

Documentation needs to be updated after support for JSON output was dropped in favour of "plain text list of commands" output.

update README for new wrapper list output

---

singularity/scripts/singularity-service-docker

Add locking around instance to avoid a race condition where multiple processes try to start the same instance at the same time. Acquiring the lock first means that the lock holder can create the instance while any other processes wait.

Add locking around instance creation

---

.github/workflows/create-release.yml
README.md

Add action to bundle irods clients (`iinit`, `ils`, `imeta`, `baton-*`) with exodus and add them to the release.

Bundle irods clients

---

docker/Makefile
docker/irods/scripts/configure_irods.sh
docker/irods/ubuntu/16.04/Dockerfile
docker/irods/ubuntu/18.04/Dockerfile
docker/irods/ubuntu/22.04/Dockerfile
docker/irods/ubuntu/22.04/Dockerfile.nightly
docker/irods_clients/ubuntu/16.04/Dockerfile
docker/irods_clients/ubuntu/18.04/Dockerfile
docker/irods_clients/ubuntu/22.04/Dockerfile
docker/irods_clients/ubuntu/22.04/Dockerfile.nightly
docker/irods_clients_dev/ubuntu/16.04/Dockerfile
docker/irods_clients_dev/ubuntu/18.04/Dockerfile
docker/irods_clients_dev/ubuntu/22.04/Dockerfile
docker/irods_clients_dev/ubuntu/22.04/Dockerfile.nightly

4.3.3 is the latest release, while 4.3.0 is has broken C API headers, so is not usable by us.

Add iRODS 4.3.3 and remove iRODS 4.3.0

---

.github/workflows/create-release.yml

The bundle is no longer needed, now that we can use Docker on the instrument.
The bundle build has been broken by changes in Actions (Node.js) and it's more cost-effective to remove than fix.

Remove creation of an Exodus bundle

---

docker/irods/scripts/configure_irods.sh

This patch was applied to get the controller working under Rosetta 2 emulation on macOS. Rosetta leaks its presence into the container and breaks Python psutil (/run/rosetta/rosetta appears instead of the true process).
However, this particular patch then breaks on Linux.

Fix the controller patch applied to iRODS 4.3.2
